import type { LucideIcon } from 'lucide-react'
import { BookOpen, Bot, ClipboardCheck, ClipboardList, FileKey, FileText, Gauge, HeartPulse, ListChecks, RadioTower, Settings, ShieldCheck, SlidersHorizontal, Users, Wrench } from 'lucide-react'

export interface NavigationItem { labelKey: string; to: string; icon: LucideIcon; permission: string; adminOnly?: boolean }
export interface NavigationGroup { labelKey: string; items: NavigationItem[] }
export const navigationGroups: NavigationGroup[] = [
  { labelKey: 'nav.resources', items: [{ labelKey: 'nav.bookSources', to: '/sources', icon: BookOpen, permission: 'book_sources.read' }, { labelKey: 'nav.sourceHealth', to: '/sources/health', icon: HeartPulse, permission: 'book_sources.read' }] },
  { labelKey: 'nav.operations', items: [{ labelKey: 'nav.engine', to: '/engine', icon: Gauge, permission: 'engine.test' }, { labelKey: 'nav.aiWorkspace', to: '/ai/workspace', icon: Bot, permission: 'ai.run' }, { labelKey: 'nav.aiTasks', to: '/ai/tasks', icon: Bot, permission: 'ai.run' }, { labelKey: 'nav.translation', to: '/translation/jobs', icon: FileText, permission: 'translation.run' }, { labelKey: 'nav.novelTasks', to: '/novel/tasks', icon: ClipboardList, permission: 'novel.manage' }] },
  { labelKey: 'nav.actions', items: [{ labelKey: 'nav.jobs', to: '/operations/jobs', icon: ListChecks, permission: 'system.jobs.manage' }, { labelKey: 'nav.agentRuns', to: '/operations/agent-runs', icon: Bot, permission: 'agent_runs.read' }, { labelKey: 'nav.deliveries', to: '/operations/deliveries', icon: RadioTower, permission: 'system.jobs.manage' }, { labelKey: 'nav.sourceBuilds', to: '/operations/source-builds', icon: Wrench, permission: 'book_sources.read' }, { labelKey: 'nav.reviewQueue', to: '/operations/review-queue', icon: ClipboardCheck, permission: 'agent_runs.read' }] },
  { labelKey: 'nav.management', items: [{ labelKey: 'nav.users', to: '/admin/users', icon: Users, permission: 'users.read', adminOnly: true }, { labelKey: 'nav.apiKeys', to: '/admin/api-keys', icon: FileKey, permission: 'api_keys.read', adminOnly: true }, { labelKey: 'nav.audit', to: '/admin/audit', icon: ShieldCheck, permission: 'system.audit.read', adminOnly: true }, { labelKey: 'nav.systemSettings', to: '/system/settings', icon: Settings, permission: 'system.settings.manage', adminOnly: true }] },
]
export function findNavigationItem(pathname: string) { return navigationGroups.flatMap((group) => group.items).sort((a, b) => b.to.length - a.to.length).find((item) => pathname === item.to || pathname.startsWith(`${item.to}/`)) }
export const consoleMark = SlidersHorizontal
